version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  filter-compiler:
    jobs:
      - path-filtering/filter:
          name: Ignore compiler-only changes
          config-path: .circleci/runtime_config_DEPRECATED.yml
          mapping: |
            compiler/*              enabled false

            .circleci/*             enabled true
            .codesandbox/*          enabled true
            fixtures/*              enabled true
            packages/*              enabled true
            scripts/*               enabled true
            .eslintignore           enabled true
            .eslintrc.js            enabled true
            .git-blame-ignore-revs  enabled true
            .gitattributes          enabled true
            .gitignore              enabled true
            .nvmrc                  enabled true
            .prettierignore         enabled true
            .prettierrc.js          enabled true
            .watchmanconfig         enabled true
            babel.config.js         enabled true
            dangerfile.js           enabled true
            netlify.toml            enabled true
            package.json            enabled true
            ReactVersions.js        enabled true
            yarn.lock               enabled true
