version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  filter-compiler:
    jobs:
      - path-filtering/filter:
          name: Ignore compiler-only changes
          config-path: .circleci/runtime_config_DEPRECATED.yml
          mapping: |
            compiler/.* skip_ci true
            .* skip_ci false
